title: "Security Notes by dbwlsdnr95"
description: "Cyber Security / Penetration Testing / Notes"

# ğŸ”¥ ìµœì‹  Just-the-Docs í…Œë§ˆ ì‚¬ìš©
remote_theme: just-the-docs/just-the-docs

url: "https://dbwlsdnr95.github.io"
permalink: pretty

# ğŸ”¥ ë‹¤í¬ëª¨ë“œ ì§€ì› (auto/light/dark ì„ íƒ ê°€ëŠ¥)
just_the_docs:
  color_scheme: auto
  enable_darkmode: true

# ìš°ì¸¡ ìƒë‹¨ Github ë§í¬
aux_links:
  "GitHub Repo": "https://github.com/dbwlsdnr95/dbwlsdnr95.github.io"
