title: "dbwlsdnr95"
description: "Security Portfolio"
theme: "just-the-docs"

url: "https://dbwlsdnr95.github.io"

aux_links:
  "GitHub Repo": "https://github.com/dbwlsdnr95/dbwlsdnr95.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
